twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        ga_code: GACode-123
    form_themes: ['bootstrap_4_layout.html.twig'] # accepte plusieurs thèmes

when@test:
    twig:
        strict_variables: true
